---
title: East To West
timezone: UTC
collections:
  case-studies:
    title: Case Studies
    output: true
  menu:
    title: Menu
    output: true
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: true
  projects:
    title: Projects
    output: true
  types:
    title: Types
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: projects
  values:
    Images:
    - Image: 
    Cover Image: "/uploads/001_brazos-lofts.jpg"
    Type: Residential
    Location: Location
permalink: pretty
sass:
  sass_dir: "./_scss"
